/*
    Walter Williams
    CarGUI
    9/19/2017

    Methods to control button behavior (setting color, instantiating car object,
    accel, brake, etc...) were created here. Also method to update the frame.
 */
package williams_java2_project_2;

import java.awt.Color;
import java.awt.Container;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;

/**
 *
 * @author PALEOHAYDUKE
 */
public class CarGUI extends javax.swing.JFrame {
    
    // initialize for case where user hits create car without selecting a color
    Color color = Color.lightGray;
    Car car;

    /**
     * Creates new form CarGUI
     */
    public CarGUI() {
        initComponents();
        groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        buttonGroup = new javax.swing.ButtonGroup();
        buttonBlack = new javax.swing.JRadioButton();
        buttonBlue = new javax.swing.JRadioButton();
        buttonCyan = new javax.swing.JRadioButton();
        buttonDarkGray = new javax.swing.JRadioButton();
        buttonGray = new javax.swing.JRadioButton();
        buttonGreen = new javax.swing.JRadioButton();
        buttonLightGray = new javax.swing.JRadioButton();
        buttonOrange = new javax.swing.JRadioButton();
        buttonPink = new javax.swing.JRadioButton();
        buttonRed = new javax.swing.JRadioButton();
        buttonWhite = new javax.swing.JRadioButton();
        buttonYellow = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        buttonCreate = new javax.swing.JButton();
        fieldMake = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldModel = new javax.swing.JTextField();
        buttonAccelerate = new javax.swing.JButton();
        buttonBrake = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPanel = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonBlack.setText("Black");
        buttonBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBlackActionPerformed(evt);
            }
        });

        buttonBlue.setText("Blue");
        buttonBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBlueActionPerformed(evt);
            }
        });

        buttonCyan.setText("Cyan");
        buttonCyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCyanActionPerformed(evt);
            }
        });

        buttonDarkGray.setText("Dark Gray");
        buttonDarkGray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDarkGrayActionPerformed(evt);
            }
        });

        buttonGray.setText("Gray");
        buttonGray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGrayActionPerformed(evt);
            }
        });

        buttonGreen.setText("Green");
        buttonGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGreenActionPerformed(evt);
            }
        });

        buttonLightGray.setText("Light Gray");
        buttonLightGray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLightGrayActionPerformed(evt);
            }
        });

        buttonOrange.setText("Orange");
        buttonOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrangeActionPerformed(evt);
            }
        });

        buttonPink.setText("Pink");
        buttonPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPinkActionPerformed(evt);
            }
        });

        buttonRed.setText("Red");
        buttonRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRedActionPerformed(evt);
            }
        });

        buttonWhite.setText("White");
        buttonWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWhiteActionPerformed(evt);
            }
        });

        buttonYellow.setText("Yellow");
        buttonYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonYellowActionPerformed(evt);
            }
        });

        jLabel1.setText("Color");

        buttonCreate.setText("Create Car");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        fieldMake.setText("Jeep");
        fieldMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMakeActionPerformed(evt);
            }
        });

        jLabel2.setText("Make");

        jLabel3.setText("Model");

        fieldModel.setText("Wrangler");
        fieldModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldModelActionPerformed(evt);
            }
        });

        buttonAccelerate.setText("Accelerate");
        buttonAccelerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAccelerateActionPerformed(evt);
            }
        });

        buttonBrake.setText("Brake");
        buttonBrake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBrakeActionPerformed(evt);
            }
        });

        textPanel.setColumns(20);
        textPanel.setRows(5);
        jScrollPane1.setViewportView(textPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonGray)
                    .addComponent(buttonYellow)
                    .addComponent(buttonGreen)
                    .addComponent(buttonLightGray)
                    .addComponent(buttonOrange)
                    .addComponent(buttonBlue)
                    .addComponent(buttonPink)
                    .addComponent(buttonCyan)
                    .addComponent(buttonRed)
                    .addComponent(buttonDarkGray)
                    .addComponent(buttonWhite)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addComponent(buttonBlack))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldModel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldMake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(buttonCreate)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonAccelerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonBrake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonBlack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonBlue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCyan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDarkGray))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonGray)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonGreen)
                            .addComponent(buttonAccelerate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLightGray)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonOrange))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBrake))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonRed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonWhite))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(buttonCreate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(buttonYellow)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    //Walter Williams
    //9/19/2017
    //updatePanel()
    // this updates the instrument panel that shows model, make, speed
    // param= none
    // returns void
    private void updatePanel(){
        String update = "Make: " + car.getMake() +"\nModel: " + car.getModel() + 
                "\nVelocity: " + car.getSpeed();
        textPanel.setText(update);
    }    
    
    //Walter Williams
    //9/19/2017
    // radio buttons
    // these buttons all set a color object to a designated color. 
    // parameters: they take an event
    // return void
    private void buttonBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBlackActionPerformed
        color = Color.black;
    }//GEN-LAST:event_buttonBlackActionPerformed

    
    
    //(String make, String model, Color color)
    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
        car = new Car(fieldMake.getText(),fieldModel.getText(),color);
        this.getContentPane().setBackground(car.getColor());
        updatePanel();
        
    }//GEN-LAST:event_buttonCreateActionPerformed

    private void buttonBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBlueActionPerformed
        color = Color.blue;
    }//GEN-LAST:event_buttonBlueActionPerformed

    private void buttonCyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCyanActionPerformed
        color = Color.cyan;
    }//GEN-LAST:event_buttonCyanActionPerformed

    private void buttonDarkGrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDarkGrayActionPerformed
        color = Color.darkGray;
    }//GEN-LAST:event_buttonDarkGrayActionPerformed

    private void buttonGrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGrayActionPerformed
        color = Color.gray;
    }//GEN-LAST:event_buttonGrayActionPerformed

    private void buttonGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGreenActionPerformed
        color = Color.green;
    }//GEN-LAST:event_buttonGreenActionPerformed

    private void buttonLightGrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLightGrayActionPerformed
        color = Color.lightGray;
    }//GEN-LAST:event_buttonLightGrayActionPerformed

    private void buttonOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrangeActionPerformed
        color = Color.orange;
    }//GEN-LAST:event_buttonOrangeActionPerformed

    private void buttonPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPinkActionPerformed
        color = Color.pink;
    }//GEN-LAST:event_buttonPinkActionPerformed

    private void buttonRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRedActionPerformed
        color = Color.red;
    }//GEN-LAST:event_buttonRedActionPerformed

    private void buttonWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWhiteActionPerformed
        color = Color.white;
    }//GEN-LAST:event_buttonWhiteActionPerformed

    private void buttonYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonYellowActionPerformed
        color = Color.yellow;
    }//GEN-LAST:event_buttonYellowActionPerformed

    // nada
    private void fieldMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMakeActionPerformed

    private void fieldModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldModelActionPerformed

    //Walter Williams
    //9/19/2017
    // buttonAcellerateActionperformed()
    // accelerates
    private void buttonAccelerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAccelerateActionPerformed
        car.accelerate();
        updatePanel();
    }//GEN-LAST:event_buttonAccelerateActionPerformed

    // brakes
    private void buttonBrakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBrakeActionPerformed
        car.brake();
        updatePanel();
    }//GEN-LAST:event_buttonBrakeActionPerformed

    // to make button selection exclusive
    private void groupButton(){
        buttonGroup.add(buttonBlack);
        buttonGroup.add(buttonBlue);
        buttonGroup.add(buttonCyan);
        buttonGroup.add(buttonDarkGray);
        buttonGroup.add(buttonGray);
        buttonGroup.add(buttonGreen);
        buttonGroup.add(buttonLightGray);
        buttonGroup.add(buttonOrange);
        buttonGroup.add(buttonPink);
        buttonGroup.add(buttonRed);
        buttonGroup.add(buttonWhite);
        buttonGroup.add(buttonYellow);
        
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAccelerate;
    private javax.swing.JRadioButton buttonBlack;
    private javax.swing.JRadioButton buttonBlue;
    private javax.swing.JButton buttonBrake;
    private javax.swing.JButton buttonCreate;
    private javax.swing.JRadioButton buttonCyan;
    private javax.swing.JRadioButton buttonDarkGray;
    private javax.swing.JRadioButton buttonGray;
    private javax.swing.JRadioButton buttonGreen;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton buttonLightGray;
    private javax.swing.JRadioButton buttonOrange;
    private javax.swing.JRadioButton buttonPink;
    private javax.swing.JRadioButton buttonRed;
    private javax.swing.JRadioButton buttonWhite;
    private javax.swing.JRadioButton buttonYellow;
    private javax.swing.JTextField fieldMake;
    private javax.swing.JTextField fieldModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textPanel;
    // End of variables declaration//GEN-END:variables
}
